src/models/__init__.py
__author__ = 'YohnCF'

src/__init__.py
__author__ = 'YohnCF'

src/app.py
from flask import Flask, render_template
from src.common.database import Database
from src.models.users.views import user_blueprint
from src.models.stores.views import store_blueprint
from src.models.alerts.views import alert_blueprint


__author__ = 'YohnCF'


app = Flask(__name__)
app.config.from_object('src.config')
app.secret_key = "123"


@app.before_first_request
def init_db():
    Database.initialize()

app.register_blueprint(user_blueprint, url_prefix="/users")
app.register_blueprint(store_blueprint, url_prefix="/stores")
app.register_blueprint(alert_blueprint, url_prefix="/alerts")


@app.route('/')
def home():
    return render_template('home.jinja2')


if __name__ == "__main__":
    app.run()

src/common/__init__.py
__author__ = 'YohnCF'

src/models/alerts/__init__.py
__author__ = 'YohnCF'

src/models/alerts/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from src.models.alerts.alert import Alert
from src.models.items.item import Item
from src.decorators import requires_login

__author__ = 'YohnCF'


alert_blueprint = Blueprint('alerts', __name__)


@alert_blueprint.route('/')
def index():
    return render_template('alerts/alerts_home.jinja2')


@alert_blueprint.route('/new', methods=['GET', 'POST'])
@requires_login
def create_alert():
    if request.method == 'POST':
        name = request.form['item_name']
        url = request.form['item_url']
        price = float(request.form['price'])

        new_item = Item(url, name)
        new_item.save_to_db()

        alert = Alert(session['email'], price, new_item._id)
        alert.load_item_price()  # This already saves to DB.
        return redirect('users/alerts')

    return render_template('alerts/create_alert.jinja2')


@alert_blueprint.route('/deactivate/<string:alert_id>')
@requires_login
def deactivate_alert(alert_id):
    Alert.get_by_id(alert_id).deactivate()
    return redirect(url_for('.get_alert_page',alert_id=alert_id))


@alert_blueprint.route('/activate/<string:alert_id>')
@requires_login
def activate_alert(alert_id):
    Alert.get_by_id(alert_id).activate()
    return redirect(url_for('.get_alert_page',alert_id=alert_id))


@alert_blueprint.route('/delete/<string:alert_id>')
@requires_login
def delete_alert(alert_id):
    Alert.get_by_id(alert_id).delete()
    return redirect(url_for('user.user_alerts'))


@alert_blueprint.route('/<string:alert_id>')
@requires_login
def get_alert_page(alert_id):
    return render_template('alerts/alert.jinja2', alert=Alert.get_by_id(alert_id))


@alert_blueprint.route('/check_price/<string:alert_id>')
@requires_login
def check_price(alert_id):
    Alert.get_by_id(alert_id).load_item_price()
    return redirect(url_for('.get_alert_page', alert_id=alert_id))


@alert_blueprint.route('/edit/<string:alert_id>', methods=['GET', 'POST'])
@requires_login
def edit_alert(alert_id):
    alert = Alert.get_by_id(alert_id)
    if request.method == 'POST':
        alert.price_limit = float(request.form['price'])
        alert.save_to_db()
        return redirect(url_for('.get_alert_page', alert_id=alert_id))

    return render_template('alerts/edit_alert.jinja2', alert=alert)

src/models/items/__init__.py
__author__ = 'YohnCF'

src/models/items/views.py
from flask import Blueprint
__author__ = 'YohnCF'


item_blueprint = Blueprint('item', __name__)


@item_blueprint.route('/<string:name>')
def item_page():
    pass

src/models/stores/__init__.py
__author__ = 'YohnCF'

src/models/stores/views.py
from flask import Blueprint, render_template, request, json, redirect, url_for

from src.models.stores.store import Store
from src.decorators import requires_admin

__author__ = 'YohnCF'

store_blueprint = Blueprint('stores', __name__)


@store_blueprint.route('/')
def index():
    stores = Store.all()
    return render_template('stores/store_list.jinja2', stores=stores)


@store_blueprint.route('/store/<string:store_id>')
def store_page(store_id):
    return render_template('stores/store.jinja2', store=Store.get_by_id(store_id))


@store_blueprint.route('/edit/<string:store_id>', methods=['GET', 'POST'])
@requires_admin
def edit_store(store_id):
    store = Store.get_by_id(store_id)
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url']
        price_tag = request.form['price_tag']
        price_query = json.loads(request.form['price_query'])
        name_tag = request.form['name_tag']
        name_query = json.loads(request.form['name_query'])

        store.name = name
        store.url_prefix =url_prefix
        store.p_tag_name = price_tag
        store.p_query = price_query
        store.n_tag_name = name_tag
        store.n_query = name_query

        store.save_to_db()
        return redirect(url_for('.store_page', store_id=store_id))

    return render_template('stores/edit_store.jinja2', store=store)


@store_blueprint.route('/delete/<string:store_id>', methods=['GET', 'POST'])
@requires_admin
def delete_store(store_id):
        Store.get_by_id(store_id).delete()
        return redirect(url_for('.index'))


@store_blueprint.route('/new',methods=['GET', 'POST'])
@requires_admin
def create_store():
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url']
        price_tag = request.form['price_tag']
        price_query = json.loads(request.form['price_query'])
        name_tag = request.form['name_tag']
        name_query = json.loads(request.form['name_query'])

        Store(name, url_prefix, price_tag, price_query, name_tag, name_query).save_to_db()

        return redirect(url_for('.index'))

    return render_template('stores/create_store.jinja2')

src/models/users/__init__.py
__author__ = 'YohnCF'

src/models/users/views.py
from flask import Blueprint, request, session, redirect, url_for, render_template
import src.models.users.errors as UserErrors
from src.decorators import requires_login
from src.models.users.user import User

__author__ = 'YohnCF'

user_blueprint = Blueprint('user', __name__)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/login.jinja2")


@user_blueprint.route('/register', methods=['GET','POST'])
def register_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.register_user(email, password):
                session['email'] = email
                return redirect(url_for(".user_alerts"))
        except UserErrors.UserError as e:
            return e.message

    return render_template("users/register.jinja2")


@user_blueprint.route('/alerts')
@requires_login
def user_alerts():
    user = User.find_by_email(session['email'])
    alerts = user.get_alerts()
    return render_template('users/alerts.jinja2',alerts=alerts)


@user_blueprint.route('/logout')
def logout_user():
    session['email']=None
    return redirect(url_for('home'))


@user_blueprint.route('/check_alerts/<string:user_id>')
def check_user_alerts(user_id):
    pass

src/templates/alerts/alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="modal-header">
        <h1>Alert<small> for {{ alert.item.name }}</small></h1>
    </div>
    <div class="card-body">
        <p>Your price limit: <strong>${{ alert.price_limit }}</strong></p>
        <p>Last price found: <strong>${{ alert.item.price }}</strong></p>
        <p class="d-inline-flex">Last checked: <strong>{{ alert.last_checked.strftime(' %d/%m/%Y - %H:%Mhrs') }}</strong>
        </p>
        <div>
            <a href="{{ alert.item.url }}" target="_blank">
                <button class="btn btn-primary btn-lg">Visit item site</button>
            </a>
            <a href="{{ url_for('alerts.edit_alert', alert_id=alert._id) }}">
                <button class="btn btn-outline-warning btn-lg">Edit alert</button>
            </a>
            <a href="{{ url_for('alerts.check_price', alert_id=alert._id) }}">
                <button class="btn btn-warning btn-lg">Check item price!</button>
            </a>
            {% if alert.active%}
                <a href="{{ url_for('alerts.deactivate_alert', alert_id=alert._id) }}">
                    <button class="btn btn-outline-danger btn-lg float-right">Deactivate alert</button>
                </a>
            {% else %}
                <a href="{{ url_for('alerts.activate_alert', alert_id=alert._id) }}">
                    <button class="btn btn-success btn-lg">Activate alert</button>
                </a>
                <a href="{{ url_for('alerts.delete_alert', alert_id=alert._id) }}">
                    <button class="btn btn-danger btn-lg float-right">Delete alert</button>
                </a>
            {% endif %}
        </div>
    </div>
{% endblock %}

src/templates/alerts/alerts_home.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="jumbotron ">
        <h1 class="display-3">Price Catcher!</h1>
        <p class="lead">Here you will find your alerts once you sign up! </p>
        <hr class="my-4">
        <p>Just Sign up with your email.</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{{ url_for('user.register_user') }}" role="button">Sign Up!</a>
        </p>
    </div>
{% endblock %}

src/templates/alerts/create_alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="modal-header">
        <h1>New Alert</h1>
    </div>
    <div class="container mt-md-5 border border-info rounded w-75 div-color">
        <form class="my-3" method="POST" action="{{ url_for('alerts.create_alert') }}">
            <div class="form-group">
                <label for="item_url">Item Name</label>
                <input type="text" class="form-control" id="item_name" name="item_name" placeholder="name">
            </div>
            <div class="form-group">
                <label for="item_url">Item URL</label>
                <input type="url" class="form-control" id="item_url" name="item_url" placeholder="www.store.com/item">
            </div>
            <div class="form-group">
                <label for="price">Price Limit</label>
                <div class="input-group">
                    <div class="input-group-addon">$</div>
                    <input type="number" step="0.01" class="form-control" id="price" name="price" placeholder="74.30"
                           aria-describedby="price_des">
                </div>
                <p id="price_des" class="text-muted">We'll send you an email when the item price is equal or lower than this </p>
            </div>
            <div>
                <button type="submit" class="btn btn-lg btn-block btn-info">Create new alert</button>
            </div>
        </form>
    </div>
{% endblock %}

src/templates/alerts/edit_alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="modal-header">
        <h1>Editing: <small>{{ alert.item.name }} alert</small></h1>
    </div>
    <div class="container mt-md-5 border border-info rounded w-75 div-color">
        <form class="my-3" method="POST">
            <div class="form-group">
                <div class="form-group">
                <label for="item_url">Item Name</label>
                <input type="text" class="form-control" id="item_name" name="item_name" value="{{ alert.item.name }}" disabled>
            </div>
            <div class="form-group">
                <label for="item_url">Item URL</label>
                <input type="url" class="form-control" id="item_url" name="item_url" value="{{ alert.item.url }}" disabled>
            </div>
                <label for="price">New price limit</label>
                <div class="input-group">
                    <div class="input-group-addon">$</div>
                    <input type="number" step="0.01" class="form-control" id="price" name="price" value="{{ alert.price_limit }}"
                           aria-describedby="price_des">
                </div>
            </div>
            <div>
                <button type="submit" class="btn btn-lg btn-block btn-info">Update</button>
            </div>
        </form>
    </div>
{% endblock %}

src/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Price Catcher</title>

    {% include 'html_dependencies.jinja2' %}

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-info">
    <a class="navbar-brand offset-md-1" href="/"><h4>Price-Catcher</h4></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a class="nav-link" href="{{ url_for('stores.index') }}">Stores<span class="sr-only">(current)</span></a></li>
            {% if session['email'] %}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('user.user_alerts') }}">Alerts</a></li>
            {% else %}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('alerts.index') }}">Alerts</a></li>
            {% endif %}
        </ul>
        {% if session['email'] %}
            <ul class="navbar-nav mr-5">
                <li class="nav-item"><a class="nav-link" href="{{ url_for('user.user_alerts') }}"><span class="oi oi-bell" title="alert" aria-hidden="true"></span> Your Alerts</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('user.logout_user') }}"><span class="oi oi-account-logout" title="account-logout" aria-hidden="true"></span> Logout</a> </li>
            </ul>
        {% else %}
            <ul class="navbar-nav mr-5">
                <li class="nav-item"><a class="nav-link" href="{{ url_for('user.register_user') }}"><span class="oi oi-person" title="sign-up" aria-hidden="true"></span> Sign up</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('user.login_user') }}"><span class="oi oi-account-login" title="account-login" aria-hidden="true"></span> Login</a> </li>
            </ul>
        {% endif %}
    </div>

</nav>

    <div class="content container mt-5">

        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

src/templates/home.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="jumbotron ">
        <h1 class="display-3">Price Catcher!</h1>
        <p class="lead">Find the product that you want.
        <br/>Set the price limit of that product
        <br/> we'll let you know when the price on the product drops to your limit</p>
        <hr class="my-4">
        <p>Just Sign up with your email.</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{{ url_for('user.register_user') }}" role="button">Sign Up!</a>
        </p>
    </div>
{% endblock %}

src/templates/html_dependencies.jinja2
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}" >
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-grid.css') }}" >
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-reboot.css') }}" >
<link rel="stylesheet" href="{{ url_for('static', filename='open-iconic/font/css/open-iconic-bootstrap.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" >

<script src="{{ url_for('static', filename='js/jquery-3.2.1.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.bundle.js') }}"></script>

src/templates/stores/create_store.jinja2
{% extends 'base.jinja2' %}
{% block content %}

      <div class="modal-header">
        <h1>Create a new store</h1>
    </div>
    <div class="container mt-md-5 mb-2 border border-info rounded w-75 div-color">
        <br/>
        <form method="post" >
        <div class="form-group">
            <label for="name">Store Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Store Name">
        </div>
        <div class="form-group">
            <label for="url">URL Prefix</label>
            <input type="text" class="form-control" id="url" name="url" placeholder="htt://www.storename.com">
        </div>
        <div class="form-group">
            <label for="price_tag">Price tag name</label>
            <input type="text" class="form-control" id="price_tag" name="price_tag"
                   placeholder="span">
        </div>
        <div class="form-group">
            <label for="price_query">Price query</label>
            <input type="text" class="form-control" id="price_query" name="price_query"
                   placeholder='{ "id" : "price-now" }'>
        </div>
        <div class="form-group">
            <label for="name_tag">Products tag name</label>
            <input type="text" class="form-control" id="name_tag" name="name_tag"
                   placeholder="span">
        </div>
        <div class="form-group">
            <label for="name_query">Name query</label>
            <input type="text" class="form-control" id="name_query" name="name_query"
                   placeholder='{ "id" : "price-now" }'>
        </div>
        <div>
            <button type="submit" class="btn btn-lg btn-block btn-info">Create</button>
            <br/>
        </div>
        </form>
    </div>

{% endblock %}

src/templates/stores/edit_store.jinja2
{% extends 'base.jinja2' %}
{% block content %}

      <div class="modal-header">
        <h1>Edit store</h1>
    </div>
    <div class="container mt-md-5 mb-2 border border-info rounded w-75 div-color">
        <br/>
        <form method="post" >
        <div class="form-group">
            <label for="name">Store Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Store Name" value="{{ store.name }}">
        </div>
        <div class="form-group">
            <label for="url">URL Prefix</label>
            <input type="text" class="form-control" id="url" name="url" placeholder="htt://www.storename.com" value="{{ store.url_prefix }}">
        </div>
        <div class="form-group">
            <label for="price_tag">Price tag name</label>
            <input type="text" class="form-control" id="price_tag" name="price_tag"
                   placeholder="span" value="{{ store.p_tag_name }}">
        </div>
        <div class="form-group">
            <label for="price_query">Price query</label>
            <input type="text" class="form-control" id="price_query" name="price_query"
                   placeholder='{ "id" : "price-now" }' value="{{ store.p_query | tojson}}">
        </div>
        <div class="form-group">
            <label for="name_tag">Products tag name</label>
            <input type="text" class="form-control" id="name_tag" name="name_tag"
                   placeholder="span" value="{{ store.n_tag_name }}">
        </div>
        <div class="form-group">
            <label for="name_query">Name query</label>
            <input type="text" class="form-control" id="name_query" name="name_query"
                   placeholder='{ "id" : "price-now" }' value="{{ store.n_query | tojson}}">
        </div>
        <div>
            <button type="submit" class="btn btn-lg btn-block btn-info">Update</button>
            <br/>
        </div>
        </form>
    </div>

{% endblock %}

src/templates/stores/store.jinja2
{% extends 'base.jinja2' %}
{% block content %}

    <div class="modal-header">
        <h1>{{ store.name }}</h1>
    </div>
    <div class="border rounded p-4">
        <p>The URL for this store is: <strong>{{ store.url_prefix }}</strong></p>
        <p>The store has the items' prices in the tag : <strong>{{ store.p_tag_name }}</strong><br/>
            Using the query: <strong>{{ store.p_query }}</strong></p>
        <p>The store identifies the items' names with the tag : <strong>{{ store.n_tag_name }}</strong><br/>
            Using the query: <strong>{{ store.n_query }}</strong></p>
        {% if session['email'] in config.ADMINS %}
            <a href="{{ url_for('stores.edit_store', store_id=store._id) }}">
                <button type="button" class="btn btn-warning btn-lg mb-1">Edit store</button>
            </a>
            <br/>
            <a href="{{ url_for('stores.delete_store', store_id=store._id) }}">
                <button type="button" class="btn btn-danger btn-lg">Delete store</button>
            </a>
        {% endif %}
    </div>

{% endblock %}

src/templates/stores/store_list.jinja2
{% extends 'base.jinja2' %}
{% block content %}

    <div class="modal-header">
        <h1>Stores<small> List of supported stores</small></h1>
        {% if session['email'] in config.ADMINS%}
            <a href="{{ url_for('stores.create_store') }}">
                <button type="button" class="btn btn-primary float-right mt-1">
                    New store <span class="oi oi-plus" title="New Alert" aria-hidden="true"></span>
                </button>
            </a>
        {% endif %}

    </div>

    <div class="container">
        {% for foo in stores %}
            <div class="card float-left ml-3 mt-3" style="width: 20em">
                <div class="card-body">
                    <h4 class="card-title">{{ foo.name}}</h4>
                    <p class="card-text">All the links of this store should start with: {{ foo.url_prefix }}</p>
                    <a href="{{ url_for('stores.store_page', store_id=foo._id) }}" class="btn btn-primary">Store info</a>
                </div>
            </div>
        {% endfor %}
                
    </div>

{% endblock %}

src/templates/users/alerts.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="modal-header">
        <h1>Alerts</h1>
        <a href="{{ url_for('alerts.create_alert') }}">
        <button type="button" class="btn btn-primary float-right mt-1" onclick="{{ url_for('alerts.create_alert') }}">
            New Alert <span class="oi oi-plus" title="New Alert" aria-hidden="true"></span>
        </button>
        </a>

    </div>
    <div class="list-group">
    {% for alert in alerts %}
        {% if alert.active %}
            <a href="{{ url_for('alerts.get_alert_page', alert_id=alert._id) }}" class="list-group-item list-group-item-action">
                <h4 class="text-dark">{{ alert.item.name }} alert</h4>
                <p class="text-secondary">Last price found: <strong>${{ alert.item.price }}</strong><br/>
                Last checked on: <strong> {{ alert.last_checked.strftime("%d-%m-%Y at %H:%M") }} </strong></p>
            </a>
        {% else %}
            <a href="{{ url_for('alerts.get_alert_page', alert_id=alert._id) }}" class="list-group-item list-group-item-action bg-light">
                <h4 class="text-secondary float-none">{{ alert.item.name }} alert <span class="oi oi-circle-x small float-right" title="Alert Inactive" aria-hidden="true"></span></h4>
                <p class="text-secondary">Last price found: <strong>${{ alert.item.price }}</strong><br/>
                Last checked on: <strong> {{ alert.last_checked.strftime("%d-%m-%Y at %H:%M") }} </strong></p>
            </a>
        {% endif %}
    {% endfor %}
    </div>
{% endblock %}

src/templates/users/login.jinja2
{% extends "base.jinja2" %}
{% block content %}

    <div class="container mt-md-5 border border-info rounded w-75 div-color">
        <form class="my-3" method="POST" action="{{ url_for('user.login_user') }}">
            <div class="form-group">
                <label for="email">Email Address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
            <div>
                <button type="submit" class="btn btn-lg btn-block btn-info">Log In</button>
            </div>
        </form>
    </div>

{% endblock %}

src/templates/users/register.jinja2
{% extends "base.jinja2" %}
{% block content %}

    <div class="container mt-md-5 border border-info rounded w-75 div-color">
        <form class="my-3" method="post" action="{{ url_for('user.register_user') }}">
            <div class="form-group">
                <label for="email">Email Address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
            </div>
            <div>
                <button type="submit" class="btn btn-lg btn-block btn-info">Sign Up</button>
            </div>
        </form>
    </div>

{% endblock %}